version: '3.8'

services:
  db:
    image: arangodb:3.10.5
    environment:
      - ARANGO_ROOT_PASSWORD=password
    volumes:
      - arango_data:/var/lib/arangodb3
    command: ["arangod", "--server.endpoint", "tcp://0.0.0.0:8529"]
    networks:
      - app-network

  nodeapp:
    build: .
    depends_on:
      - db
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=production
      - ARANGO_URL=http://db:8529
      - ARANGO_USER=root
      - ARANGO_PASSWORD=password
      - ARANGO_DB=city_data
      - PORT=3000
    command: sh -c "npm run import && npm start"
    networks:
      - app-network

volumes:
  arango_data:

networks:
  app-network:
    driver: bridge