version: '3.8'

services:
  arango:
    image: arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
    command: ["arangod", "--server.endpoint", "tcp://0.0.0.0:8529"]

  nodeapp:
    build: .
    depends_on:
      - arango
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ARANGO_URL=http://arango:8529
      - ARANGO_USER=root
      - ARANGO_PASSWORD=password
      - ARANGO_DB=city_data
      - PORT=3000
    # Удаляем монтирование тома
    # volumes:
    #   - .:/usr/src/app
    command: sh -c "npm run import && npm start"

volumes:
  arango_data:
