version: '3.8'
services:
  arango:
    image: arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
  nodeapp:
    build: .
    depends_on:
      - arango
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
volumes:
  arango_data:
